name: APK Build

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: |
          sdkmanager "build-tools;36.0.0"
          sdkmanager "build-tools;29.0.3"

      - name: Build Debug APK
        run: bash ./gradlew :androidApp:assembleFossDebug --stacktrace

      - name: Build APK
        run: bash ./gradlew :androidApp:assembleFossRelease --stacktrace

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: androidApp/build/outputs/apk/foss/release
          signingKeyBase64: ${{ secrets.KEYSTORE_B64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: kai-foss-debug
          path: androidApp/build/outputs/apk/foss/debug/androidApp-foss-debug.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: androidApp/build/outputs/apk/foss/release/androidApp-foss-release-signed.apk
